name: Deployment

on:
  push:
    branches: [user/Gurtej/#149]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy-frontend:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout frontend
        run: cd bookyrm_frontend

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          repository: gurtejboparai/bookwyrm
          tags: latest, ${{github.run_number}}
