name: Deployment

on:
  push:
    branches: [user/Gurtej/#149]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy-frontend:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Logging into Docker hub
        uses: docker/login-action@v1
          with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          repository: gurtejboparai/bookwyrm

      - name: Build and push Docker image
        working-directory: ./bookwyrm_frontend
        run: docker build -t bookwyrm_frontend .
        run: docker push gurtejboparai/bookwyrm
