name: frontend_testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./bookwyrm_frontend
        run: npm install

      - name: Build
        working-directory: ./bookwyrm_frontend
        run: npm run build
  
      - name: Run Tests
        working-directory: ./bookwyrm_frontend
        run: npm run test